default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  username: admin
  password: pass
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: library_management_system_development

test:
  <<: *default
  database: library_management_system_test

production:
  <<: *default
  database: library_management_system
